source 'https://cdn.cocoapods.org/'
#source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'
 inhibit_all_warnings!

#plugin 'cocoapods-binary'
use_frameworks!
#use_modular_headers!

target 'LAMB Wallet' do 
  
  pod 'AFNetworking', '~> 4.0.1'
  pod 'YYCache', '~> 1.0.4'
  pod 'YYModel', '~> 1.0.4'
  pod 'Masonry'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'MJRefresh', '~> 3.5.0'
  pod 'YYCategories', '~> 1.0.4'
  pod 'IQKeyboardManager'
  pod 'ReactiveObjC', '~> 3.1.1'
  pod 'DZNEmptyDataSet', '~> 1.8.1'
  pod 'TPKeyboardAvoiding', '~> 1.3.5'
  pod 'FCAlertView'
  pod 'UITableViewDynamicLayoutCacheHeight'
  pod 'TrustWalletCore'
  pod 'TrezorCrypto'
#  pod 'TrustCore', :git=>'https://github.com/TrustWallet/trust-core', :branch=>'master'
  pod 'ActionSheetPicker-3.0'
  pod 'DoraemonKit/Core', '~> 3.0.4', :configurations => ['Debug']
#  pod 'CoreBitcoin',:podspec => 'https://raw.github.com/oleganza/CoreBitcoin/master/CoreBitcoin.podspec'
#pod 'CoreBitcoin', :git => 'https://gitee.com/mirrors/corebitcoin'
pod 'CoreBitcoin', :git => 'https://github.com/Ssunnys/CoreBitcoin.git'
pod 'CBSecp256k1'


end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end
