source 'https://cdn.cocoapods.org/'

# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0' 
 inhibit_all_warnings!

target 'LAMB Wallet' do 
    use_frameworks!
	pod 'AFNetworking', '~> 4.0.1' 
  pod 'YYCache', '~> 1.0.4'
  pod 'YYModel', '~> 1.0.4'
  pod 'Masonry'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'MJRefresh', '~> 3.5.0'
  pod 'YYCategories', '~> 1.0.4'
  pod 'IQKeyboardManager'
  pod 'ReactiveObjC', '~> 3.1.1'
  pod 'DZNEmptyDataSet', '~> 1.8.1'
  pod 'TPKeyboardAvoiding', '~> 1.3.4'

  pod 'CMPageTitleView'
  pod 'DoraemonKit/Core', '~> 3.0.4', :configurations => ['Debug']
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end
